### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Nou4r** [nbqofficial/norsefire#1]
https://i.imgur.com/2AOsh47.png

Would be useful to post your solution settings

**Comment by nbqofficial** [comment]
> https://i.imgur.com/2AOsh47.png
> 
> Would be useful to post your solution settings

 disable 'treat warnings as errors' in C/C++ tab

**Comment by Nou4r** [comment]
Hey, was already set as that.

**Comment by nbqofficial** [comment]
> Hey, was already set as that.

you should add me on discord if you are having troubles nbq#7049
